services:
  postgres:
    image: postgres:17-alpine
    container_name: airline-assistant-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airline_assistant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

#  ollama:
#    image: ollama/ollama:latest
#    container_name: airline-assistant-ollama
#    ports:
#      - "11434:11434"
#    volumes:
#      - ollama_data:/root/.ollama
#    environment:
#      - OLLAMA_HOST=0.0.0.0
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 30s
#    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:
