spring:
  application:
    name: airlines-assistant-spring-ai
  datasource:
    url: jdbc:postgresql://localhost:5432/airline_assistant
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude:
      - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral:7b
          temperature: 0.7
          max-tokens: 1000
      embedding:
        options:
          model: nomic-embed-text

server:
  port: 9080

logging:
  level:
    com.airline.assistant: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.ai.ollama: TRACE

# Profile indicator
airline:
  assistant:
    ai-provider: "Ollama (Local)"
    model-name: "mistral:7b"
