spring:
  application:
    name: airlines-assistant-spring-ai
  autoconfigure:
    exclude:
      - org.springframework.ai.model.ollama.autoconfigure.OllamaChatAutoConfiguration
      - org.springframework.ai.model.ollama.autoconfigure.OllamaEmbeddingAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/airline_assistant
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-tokens: 1000
      embedding:
        options:
          model: text-embedding-3-small

server:
  port: 9080

logging:
  level:
    com.airline.assistant: DEBUG
    org.springframework.ai: DEBUG

# Profile indicator
airline:
  assistant:
    ai-provider: "OpenAI (Cloud)"
    model-name: "gpt-4o-mini"
    safeguard:
      enabled: true
      sensitivity-level: "MEDIUM"
      warning-message: "I need to maintain professional communication standards. Let me help you with your airline travel needs in an appropriate manner."
      profanity-keywords:
        - "damn"
        - "hell"
        - "crap"
        - "stupid"
        - "idiot"
        - "moron"
        - "dumb"
      inappropriate-keywords:
        - "inappropriate"
        - "harmful"
        - "offensive"
        - "rude"
        - "disrespectful"
        - "unprofessional"
        - "threatening"
        - "abusive"
        - "discriminatory"
      policy-violation-keywords:
        - "bomb"
        - "weapon"
        - "hijack"
        - "terrorist"
        - "attack"
        - "violence"
        - "illegal"
        - "drugs"
        - "smuggle"
        - "contraband"
